### ISSUE TITLE
Don't always overwrite git@ with https://

### ISSUE THREAD

**Issue by ipsi** [vito/gosub#1]
Forcing submodules to use `https` is problematic when using git keys to authenticate with `git@` (e.g. to access private repos).

Obviously the `.gitmodules` entries should use `https://` when the repo is publicly available, as that is a better user experience for anyone whose git key does not have access to that repo. However, in the case where we have private repos, we want the `.gitmodules` file to continue to use `git@`

Andrew & @robdimsdale

**Comment by vito** [comment]
I won't be doing this any time soon; it's way too annoying having a public repo constantly have its submodules switch between `git@` and `https://`. You could have a local `.gitconfig` that configures `insteadOf` or `pushInsteadOf`:

https://git-scm.com/docs/git-config

e.g.

https://github.com/vito/dotfiles/blob/master/git/.gitconfig#L9-L11
